name: 'set-env-vars-multiline'
description: 'set-env-vars-multiline'
author: 'Felipe Baisi'

inputs:
  MULTI_LINE_VARS:
    required: true
    description: 'MULTI_LINE_VARS'

runs:
  using: 'node16'
  main: 'dist/index.js'
